$(document).ready(function(){
  $('#display').load('screenInfo.html', function(){
    $('#grtBtn').mousedown(function(){
      $('#csExplain').load('text/grtIntro.txt')
      $('#csExplain').show();
    });
    $('#wisBtn').mousedown(function(){
      $('#csExplain').load('text/wisIntro.txt')
      $('#csExplain').show();
    });
    $('#mnpBtn').mousedown(function(){
      $('#csExplain').load('text/mnpIntro.txt')
      $('#csExplain').show();
    });
    $('#knoBtn').mousedown(function(){
      $('#csExplain').load('text/knoIntro.txt')
      $('#csExplain').show();
    });
    $('#judBtn').mousedown(function(){
      $('#csExplain').load('text/judIntro.txt')
      $('#csExplain').show();
    });
    $('#dsrBtn').mousedown(function(){
      $('#csExplain').load('text/dsrIntro.txt')
      $('#csExplain').show();
    });
  });
});