console.log('character: start');
character.nam = nam;
character.gnd = gnd;
character.age = age;
character.rac = rac;
character.hmt = hmt;
character.bgs = bgs;
character.upb = upb;
character.qrk = function(){};
character.str = new stat('strength',str,0);
character.spd = new stat('speed',spd,0);
character.stm = new stat('stamina',stm,0);
character.grt = new stat('growth',grt,0);
character.wis = new stat('wisdom',wis,0);
character.mnp = new stat('manipulation',mnp,0);
character.kno = new stat('knowledge',kno,0);
character.jud = new stat('judgement',jud,0);
character.dsr = new stat('desire',dsr,0);
console.log('character: end');